import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — EmailHQ",
  description: "The terms that govern your use of EmailHQ.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: [
      {
        heading: "",
        body: "By accessing or using EmailHQ (the Service), you agree to be bound by these Terms of Service (Terms). If you do not agree, do not use the Service. These Terms apply to all users of EmailHQ, including users who connect their Google accounts.",
      },
    ],
  },
  {
    title: "2. Description of Service",
    content: [
      {
        heading: "",
        body: "EmailHQ is an AI-powered email management tool that connects to your Google account (Gmail, Calendar, and Drive) via OAuth 2.0. The Service classifies incoming emails, applies Gmail labels, and generates draft replies using AI. EmailHQ is provided on an \"as is\" and \"as available\" basis.",
      },
    ],
  },
  {
    title: "3. Account & Google OAuth",
    content: [
      {
        heading: "Account Creation",
        body: "You must sign in with a valid Google account to use EmailHQ. You are responsible for maintaining the confidentiality of your account and for all activity that occurs under it.",
      },
      {
        heading: "Google Permissions",
        body: "You grant EmailHQ permission to access your Gmail, Google Calendar, and Google Drive data as described during the OAuth consent flow. You may revoke this access at any time via your Google Account settings. Revoking access will disable EmailHQ functionality.",
      },
      {
        heading: "Accurate Information",
        body: "You agree to provide accurate information when creating your account and to keep it up to date.",
      },
    ],
  },
  {
    title: "4. Acceptable Use",
    content: [
      {
        heading: "Permitted Use",
        body: "You may use EmailHQ solely for lawful personal or business email management purposes in accordance with these Terms.",
      },
      {
        heading: "Prohibited Conduct",
        body: "You must not: (a) use the Service to send spam or unsolicited messages; (b) attempt to reverse engineer, decompile, or extract source code; (c) use the Service in a way that violates any applicable law or regulation; (d) attempt to gain unauthorised access to any part of the Service or its infrastructure; (e) use the Service to process data that infringes third-party intellectual property rights.",
      },
      {
        heading: "AI-Generated Content",
        body: "Draft replies generated by EmailHQ are AI-generated suggestions. You are solely responsible for reviewing any draft before sending. EmailHQ does not guarantee the accuracy, appropriateness, or completeness of AI-generated content.",
      },
    ],
  },
  {
    title: "5. Privacy",
    content: [
      {
        heading: "",
        body: "Your use of the Service is also governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service you agree to the collection and use of information as described in the Privacy Policy.",
      },
    ],
  },
  {
    title: "6. Intellectual Property",
    content: [
      {
        heading: "Our IP",
        body: "EmailHQ and its original content, features, and functionality are owned by EmailHQ and are protected by international copyright, trademark, and other intellectual property laws.",
      },
      {
        heading: "Your Data",
        body: "You retain all ownership rights to your email content and other data. By using the Service you grant EmailHQ a limited, non-exclusive licence to process your data solely for the purpose of providing the Service to you.",
      },
    ],
  },
  {
    title: "7. Disclaimer of Warranties",
    content: [
      {
        heading: "",
        body: "THE SERVICE IS PROVIDED \"AS IS\" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. YOU USE THE SERVICE AT YOUR OWN RISK.",
      },
    ],
  },
  {
    title: "8. Limitation of Liability",
    content: [
      {
        heading: "",
        body: "TO THE FULLEST EXTENT PERMITTED BY LAW, EMAILHQ SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF OR INABILITY TO USE THE SERVICE, EVEN IF EMAILHQ HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT SHALL EMAILHQ'S TOTAL LIABILITY EXCEED THE AMOUNT YOU PAID (IF ANY) TO USE THE SERVICE IN THE TWELVE MONTHS PRECEDING THE CLAIM.",
      },
    ],
  },
  {
    title: "9. Indemnification",
    content: [
      {
        heading: "",
        body: "You agree to indemnify and hold harmless EmailHQ and its officers, directors, employees, and agents from any claims, damages, losses, liabilities, costs, or expenses (including reasonable legal fees) arising out of your use of the Service, your violation of these Terms, or your violation of any third-party rights.",
      },
    ],
  },
  {
    title: "10. Termination",
    content: [
      {
        heading: "By You",
        body: "You may stop using the Service at any time. You may delete your account by contacting support@emailhq.app.",
      },
      {
        heading: "By Us",
        body: "We reserve the right to suspend or terminate your access to the Service at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, third parties, or the public.",
      },
      {
        heading: "Effect of Termination",
        body: "Upon termination, your right to use the Service immediately ceases. Provisions that by their nature should survive termination shall survive, including ownership provisions, warranty disclaimers, and limitations of liability.",
      },
    ],
  },
  {
    title: "11. Third-Party Services",
    content: [
      {
        heading: "",
        body: "The Service integrates with Google APIs and Groq. Your use of those services is subject to their respective Terms of Service and Privacy Policies. EmailHQ is not responsible for the availability or conduct of third-party services.",
      },
    ],
  },
  {
    title: "12. Governing Law",
    content: [
      {
        heading: "",
        body: "These Terms shall be governed by and construed in accordance with the laws of England and Wales, without regard to its conflict of law provisions. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales.",
      },
    ],
  },
  {
    title: "13. Changes to Terms",
    content: [
      {
        heading: "",
        body: "We reserve the right to modify these Terms at any time. We will provide notice of material changes by posting the updated Terms in the app or by email. Your continued use of the Service after changes take effect constitutes your acceptance of the revised Terms.",
      },
    ],
  },
  {
    title: "14. Contact",
    content: [
      {
        heading: "",
        body: "Questions about these Terms? Contact us at legal@emailhq.app or by mail at EmailHQ, 1 Canada Square, London, E14 5AB, United Kingdom.",
      },
    ],
  },
];

export default function TermsPage() {
  return (
    <div
      className="min-h-screen font-body"
      style={{ background: "var(--lp-bg-primary)", color: "var(--lp-text-primary)" }}
    >
      {/* Nav bar back link */}
      <div
        className="border-b"
        style={{ borderColor: "var(--lp-border)", background: "var(--lp-surface)" }}
      >
        <div className="max-w-screen-md mx-auto px-4 md:px-8 h-14 flex items-center justify-between">
          <Link
            href="/"
            className="font-heading font-bold text-[16px]"
            style={{ color: "var(--lp-text-primary)" }}
          >
            EmailHQ
          </Link>
          <Link
            href="/"
            className="text-[13px] font-body transition-opacity hover:opacity-70"
            style={{ color: "var(--lp-text-muted)" }}
          >
            ← Back to home
          </Link>
        </div>
      </div>

      {/* Content */}
      <div className="max-w-screen-md mx-auto px-4 md:px-8 py-16 md:py-24">
        <p
          className="text-[11px] font-semibold uppercase tracking-widest mb-4"
          style={{ color: "var(--lp-text-muted)" }}
        >
          Legal
        </p>
        <h1
          className="font-heading font-bold mb-3"
          style={{ fontSize: "clamp(2rem, 5vw, 3rem)", lineHeight: 1.1, color: "var(--lp-text-primary)" }}
        >
          Terms of Service
        </h1>
        <p className="text-[14px] mb-12" style={{ color: "var(--lp-text-muted)" }}>
          Last updated: 1 April 2026
        </p>

        <p
          className="text-[15px] leading-relaxed mb-12 pb-12 border-b"
          style={{ color: "var(--lp-text-secondary)", borderColor: "var(--lp-border)" }}
        >
          Please read these Terms of Service carefully before using EmailHQ. These Terms constitute a
          legally binding agreement between you and EmailHQ regarding your use of the Service.
        </p>

        <div className="space-y-12">
          {sections.map((section) => (
            <div key={section.title}>
              <h2
                className="font-heading font-bold text-[1.25rem] mb-6"
                style={{ color: "var(--lp-text-primary)" }}
              >
                {section.title}
              </h2>
              <div className="space-y-5">
                {section.content.map((item, i) => (
                  <div key={i}>
                    {item.heading && (
                      <p
                        className="font-body font-semibold text-[14px] mb-1"
                        style={{ color: "var(--lp-text-primary)" }}
                      >
                        {item.heading}
                      </p>
                    )}
                    <p
                      className="text-[14px] leading-relaxed"
                      style={{ color: "var(--lp-text-secondary)" }}
                    >
                      {item.body}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer links */}
        <div
          className="mt-16 pt-8 border-t flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
          style={{ borderColor: "var(--lp-border)" }}
        >
          <p className="text-[13px]" style={{ color: "var(--lp-text-muted)" }}>
            © {new Date().getFullYear()} EmailHQ. All rights reserved.
          </p>
          <div className="flex items-center gap-6">
            <Link href="/terms" className="text-[13px] transition-opacity hover:opacity-70" style={{ color: "var(--lp-accent)" }}>
              Terms of Service
            </Link>
            <Link href="/privacy" className="text-[13px] transition-opacity hover:opacity-70" style={{ color: "var(--lp-text-muted)" }}>
              Privacy Policy
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
